version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - static-data:/web/static
    networks:
      - nginx_network
    environment:
      - ENVIRONMENT_FILE=.env.local
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    entrypoint: /entrypoint.sh
    command: >
      bash -c "celery -A web worker --loglevel=info &
      gunicorn web.wsgi:application --bind 0.0.0.0:8000 --timeout 120"

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - nginx_network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 3

volumes:
  static-data:
    external: true

networks:
  nginx_network:
    external: true