# Generated by Django 5.2 on 2025-05-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sexual_orientation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Straight'), (2, 'Gay'), (3, 'Lesbian'), (4, 'Bisexual'), (5, 'Other')], null=True),
        ),
    ]
