name: Deploy to server

on:
  push:
    branches:
      - main  # основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest  # запускаем на последней версии Ubuntu
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Клонируем репозиторий

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 77.239.96.124 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh root@77.239.96.124 << 'EOF'
          set -e
          cd ~
          rm -rf keramicheskiy.ru/
          git clone https://github.com/keramicheskiy/keramicheskiy.ru.git
          cd keramicheskiy.ru/
          docker-compose down
          docker-compose up --build -d
        EOF
